import type { IconType } from "react-icons";
import {
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiRedux,
  SiTailwindcss,
  SiHtml5,
  SiCss,
  SiNodedotjs,
  SiExpress,
  SiPhp,
  SiPostgresql,
  SiMongodb,
  SiMysql,
  SiFirebase,
  SiPrisma,
  SiVercel,
  SiRender,
  SiNeon,
  SiStripe,
  SiGit,
  SiGithub,
  SiPostman,
  SiVite,
  SiFigma,
  SiWordpress,
  SiLinux,
} from "react-icons/si";
import { FaDatabase, FaStore, FaRoute, FaKey, FaPalette, FaCode } from "react-icons/fa";

const iconMap: Record<string, IconType> = {
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiRedux,
  SiTailwindcss,
  SiHtml5,
  SiCss,
  SiNodedotjs,
  SiExpress,
  SiPhp,
  SiPostgresql,
  SiMongodb,
  SiMysql,
  SiFirebase,
  SiPrisma,
  SiVercel,
  SiRender,
  SiNeon,
  SiStripe,
  SiGit,
  SiGithub,
  SiPostman,
  SiVite,
  SiFigma,
  SiWordpress,
  SiLinux,
  FaDatabase,
  FaStore,
  FaRoute,
  FaKey,
  FaPalette,
};

export function SkillIcon({ name }: { name: string }) {
  const Icon = iconMap[name] ?? FaCode;
  return <Icon />;
}